name: tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Test Homework 1
      run: cd ./src/Homework1; python main.py -g all
    - run: echo "🍏 This job's status is ${{ job.status }}."
    - name: Test Homework 2
      run: cd ./src/Homework2; python main.py -g all
    - run: echo "🍏 This job's status is ${{ job.status }}."
    - name: Test Homework 3
      run: cd ./src/Homework3; python main.py -g all
    - run: echo "🍏 This job's status is ${{ job.status }}."
    - name: Test Homework 4
      run: cd ./src/Homework4; python main.py -g all
    - run: echo "🍏 This job's status is ${{ job.status }}."
